### ISSUE TITLE
Error: Module version mismatch in master

### ISSUE THREAD

**Issue by gokulnath** [TrustWallet/trust-ray#245]
The application is crashing, logs below.
```
$ ./trust logs

app_1      | 12:22:20 PM - Starting compilation in watch mode...
app_1      | 12:22:26 PM - Compilation complete. Watching for file changes.
app_1      | [nodemon] 1.14.3
app_1      | [nodemon] to restart at any time, enter `rs`
app_1      | [nodemon] watching: *.*
app_1      | [nodemon] starting `node dist/Server.js`
app_1      | module.js:597
app_1      |   return process.dlopen(module, path._makeLong(filename));
app_1      |                  ^
app_1      | 
app_1      | Error: Module version mismatch. Expected 48, got 57.
app_1      |     at Error (native)
app_1      |     at Object.Module._extensions..node (module.js:597:18)
app_1      |     at Module.load (module.js:487:32)
app_1      |     at tryModuleLoad (module.js:446:12)
app_1      |     at Function.Module._load (module.js:438:3)
app_1      |     at Module.require (module.js:497:17)
app_1      |     at require (internal/module.js:20:19)
app_1      |     at Object.<anonymous> (/opt/server/node_modules/scrypt/index.js:3:20)
app_1      |     at Module._compile (module.js:570:32)
app_1      |     at Object.Module._extensions..js (module.js:579:10)
app_1      |     at Module.load (module.js:487:32)
app_1      |     at tryModuleLoad (module.js:446:12)
app_1      |     at Function.Module._load (module.js:438:3)
app_1      |     at Module.require (module.js:497:17)
app_1      |     at require (internal/module.js:20:19)
app_1      |     at Object.<anonymous> (/opt/server/node_modules/scrypt.js/node.js:1:76)
app_1      |     at Module._compile (module.js:570:32)
app_1      |     at Object.Module._extensions..js (module.js:579:10)
app_1      |     at Module.load (module.js:487:32)
app_1      |     at tryModuleLoad (module.js:446:12)
app_1      |     at Function.Module._load (module.js:438:3)
app_1      |     at Module.require (module.js:497:17)
app_1      |     at require (internal/module.js:20:19)
app_1      |     at Object.<anonymous> (/opt/server/node_modules/web3-eth-accounts/src/index.js:35:16)
app_1      |     at Module._compile (module.js:570:32)
app_1      |     at Object.Module._extensions..js (module.js:579:10)
app_1      |     at Module.load (module.js:487:32)
app_1      |     at tryModuleLoad (module.js:446:12)
app_1      |     at Function.Module._load (module.js:438:3)
app_1      |     at Module.require (module.js:497:17)
app_1      |     at require (internal/module.js:20:19)
app_1      |     at Object.<anonymous> (/opt/server/node_modules/web3-eth/src/index.js:36:16)
app_1      |     at Module._compile (module.js:570:32)
app_1      |     at Object.Module._extensions..js (module.js:579:10)
app_1      | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by vikmeup** [comment]
@gokulnath The person responsible for docker never finished it, so never worked. 

You can try running locally instead.
